In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('weather_data.csv',parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
type(df.day[0])

In [13]:
df.set_index('day',inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
df.fillna(0, inplace=True)
df

In [ ]:
df

In [ ]:
df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed': df.windspeed.mean(),
    'event': 'No Event'
})

In [ ]:
df.ffill(inplace=True, axis=0)
df

In [4]:
df.dtypes

temperature    float64
windspeed      float64
event              str
dtype: object

In [10]:
df[["temperature", "windspeed"]] = df[["temperature", "windspeed"]].interpolate()
df

            temperature  windspeed   event
day
2017-01-01         32.0      6.000    Rain
2017-01-04         30.0      9.000   Sunny
2017-01-05         28.0      8.000    Snow
2017-01-06         30.0      7.000     NaN
2017-01-07         32.0      7.275    Rain
2017-01-08         32.7      7.550   Sunny
2017-01-09         33.4      7.825     NaN
2017-01-10         34.1      8.100  Cloudy
2017-01-11         40.0     12.000   Sunny

In [20]:
df.dropna(how='all')

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [21]:
df.dropna(thresh=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny