# Pandas Introduction 1

**Using normal pythhon code**

In [2]:
import csv

In [3]:
def calaculate_rating(data,industry=None):
    ratings = []
    for row in data:
        # print(row)
        if row[3]!= "NULL" and (not industry or row[1] == industry):
            ratings.append(float(row[3]))
    max_ratings = max(ratings)
    min_ratings = min(ratings)
    avg_ratings = sum(ratings)/len(ratings)
    return max_ratings, min_ratings, avg_ratings

    
with open("movies.csv") as f:
    data = list(csv.reader(f))
    header = data[0]
    data = data[1:]

max_ratings, min_ratings, avg_ratings = calaculate_rating(data)
print(f'All Records: Min rating: {min_ratings}, Max rating: {max_ratings}, Avg rating: {round(avg_ratings,2)}')

max_ratings, min_ratings ,avg_ratings = calaculate_rating(data, industry='Bollywood')
print(f'All Bollywood: Min rating: {min_ratings}, Max rating: {max_ratings}, Avg rating: {round(avg_ratings,2)}')

max_ratings, min_ratings ,avg_ratings = calaculate_rating(data, industry='Hollywood')
print(f'All Hollywood: Min rating: {min_ratings}, Max rating: {max_ratings}, Avg rating: {round(avg_ratings,2)}')

All Records: Min rating: 1.9, Max rating: 9.3, Avg rating: 7.92
All Bollywood: Min rating: 1.9, Max rating: 8.4, Avg rating: 7.66
All Hollywood: Min rating: 6.8, Max rating: 9.3, Avg rating: 8.13

**Using Pandas**

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('movies.csv')
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu

In [9]:
df.tail(5)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [10]:
df.sample(4)

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.0,2202.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi

In [12]:
df.shape

(37, 10)

In [15]:
df["imdb_rating"]

0     8.3
1     7.0
2     6.8
3     7.9
4     6.8
5     9.3
6     8.6
7     8.0
8     8.5
9     7.9
10    8.6
11    7.8
12    9.2
13    9.0
14    9.0
15    8.2
16    8.5
17    8.4
18    8.4
19    6.9
20    7.8
21    8.0
22    8.4
23    7.4
24    7.2
25    8.3
26    8.1
27    8.1
28    NaN
29    8.3
30    8.1
31    1.9
32    8.4
33    8.4
34    7.6
35    8.0
36    8.0
Name: imdb_rating, dtype: float64

In [18]:
df.imdb_rating.min(), df.imdb_rating.max(), df.imdb_rating.mean()

(np.float64(1.9), np.float64(9.3), np.float64(7.919444444444445))

In [22]:
df_h = df[df.industry == 'Hollywood']
df_b = df[df.industry == 'Bollywood']

In [26]:
df_h.imdb_rating.min(),df.imdb_rating.max(), df.imdb_rating.mean()

(np.float64(6.8), np.float64(9.3), np.float64(7.919444444444445))

In [27]:
df_b.imdb_rating.min(),df_b.imdb_rating.max(), df_b.imdb_rating.mean()

(np.float64(1.9), np.float64(8.4), np.float64(7.656250000000001))

In [30]:
df = pd.read_csv('movies.csv')
print(f'All Movie ratings: Min: {df.imdb_rating.min()}, Max: {df.imdb_rating.max()}, Average: {df.imdb_rating.mean()}')

df_h = df[df.industry == 'Hollywood']
df_b = df[df.industry == 'Bollywood']

print(f'Hollwood ratings: Min: {df_h.imdb_rating.min()}, Max: {df_h.imdb_rating.max()}, Average: {df_h.imdb_rating.mean()}')

All Movie ratings: Min: 1.9, Max: 9.3, Average: 7.919444444444445
Hollwood ratings: Min: 6.8, Max: 9.3, Average: 8.130000000000003